#!/usr/bin/env python

# Script for ploting an image of the mean single-trial estimates for each task

# Adapted from code available in the GitHub repository (https://github.com/GttNeuro/Guo-Lab_datapaper)


import os
import nibabel as nib
import pandas as pd
from nilearn.image import mean_img
from nilearn.plotting import plot_stat_map
import matplotlib.pyplot as plt
import re  

root = '../data/derivatives/singletrial'
output_dir = '../data/derivatives/figure'


data = []
for sub in os.listdir(root):

    if '001' <= sub.split('-')[1] <= '077':
        sub_dir = os.path.join(root, sub)
        if os.path.isdir(sub_dir):
            for file in os.listdir(sub_dir):

                if file.endswith('singletrial-Act.nii.gz') and 'task-LanguageControl' in file:
                    task = re.search('task-(.*)_run', file).group(1)
                    file_path = os.path.join(sub_dir, file)
                    data.append([sub, task, file_path])

df = pd.DataFrame(data, columns=['sub', 'task', 'image'])

task = 'LanguageControl'
task_images = df[df['task'] == task]['image'].tolist()
if task_images:
    mean_image = mean_img(task_images)
    
    display = plot_stat_map(mean_image, cut_coords=(-10, -5, 0, 5, 10, 15, 20, 25),
                            display_mode='z', title=f'Mean z for {task} task',
                            colorbar=True, cmap='bwr', vmax=0.3)
    output_path = os.path.join(output_dir, f'Mean-z_task-{task}_vmax03.png')
    display.savefig(output_path, dpi=300)
    plt.close()

print("Image have been saved in:", output_dir)
